{
 "title": "spacebox",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "15m",
 "templating": {
  "list": [
   { "name": "space", "label": "space", "query": "prometheus" },
   { "name": "clickhouse", "label": "database", "query": "grafana-clickhouse-datasource" }
  ]
 },
 "panels": [
  {
   "title": "Total blocks in Clickhouse",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count() FROM raw_block final"
    }
   ]
  },
  {
   "title": "last block height in Clickhouse",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT height FROM raw_block final ORDER BY height DESC LIMIT 1"
    }
   ]
  },
  {
   "title": "count of skipped block_results",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(*) FROM (\n WITH blocks AS (\n SELECT\n  toUInt64(min(height)) as st,\n  toUInt64(max(height)) as ed\n FROM\n  spacebox.raw_block_results\n )\n SELECT\n  arrayJoin(range(st, ed)) as _height FROM blocks\n) AS _blocks\nLEFT JOIN (SELECT toUInt64(height) as height FROM spacebox.raw_block_results) AS blocks ON _blocks._height = blocks.height\nWHERE height = 0;"
    }
   ]
  },
  {
   "title": "count of skipped blocks",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 13, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(*) FROM (\n WITH blocks AS (\n SELECT\n  toUInt64(min(height)) as st,\n  toUInt64(max(height)) as ed\n FROM\n  spacebox.raw_block\n )\n SELECT\n  arrayJoin(range(st, ed)) as _height FROM blocks\n) AS _blocks\nLEFT JOIN (SELECT toUInt64(height) as height FROM spacebox.raw_block) AS blocks ON _blocks._height = blocks.height\nWHERE height = 0;"
    }
   ]
  },
  {
   "title": "skipped blocks in begin_block_events",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(*) FROM (\n\tSELECT height, msgs.height as _height FROM (\n\t\tSELECT height FROM spacebox.raw_block_results\n\t\tWHERE begin_block_events != ''\n\t\tGROUP BY height \n\t) as txs\n\tLEFT JOIN (select height from spacebox.begin_block_events GROUP BY height ) as msgs ON txs.height = msgs.height\n)\nWHERE _height = 0"
    }
   ]
  },
  {
   "title": "skipped blocks in end_block_events",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(*) FROM (\n\tSELECT height, msgs.height as _height FROM (\n\t\tSELECT height FROM spacebox.raw_block_results\n\t\tWHERE end_block_events != ''\n\t\tGROUP BY height \n\t) as txs\n\tLEFT JOIN (select height from spacebox.end_block_events GROUP BY height ) as msgs ON txs.height = msgs.height\n)\nWHERE _height = 0"
    }
   ]
  },
  {
   "title": "skipped blocks in txs_events",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(*) FROM (\n\tSELECT height, msgs.height as _height FROM (\n\t\tSELECT height FROM spacebox.raw_block_results\n\t\tWHERE JSONExtractString(JSONExtractString(arrayJoin(JSONExtractArrayRaw(JSONExtractString(txs_results)))), 'events') != '[]'\n\t\tGROUP BY height \n\t) as txs\n\tLEFT JOIN (select height from spacebox.txs_events GROUP BY height ) as msgs ON txs.height = msgs.height\n)\nWHERE _height = 0"
    }
   ]
  },
  {
   "title": "Double block_results",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH ch AS (\n\tSELECT height, count(height) as c FROM spacebox.raw_block_results\n\tGROUP BY height\n)\nSELECT count(*) as count FROM ch WHERE c != 1"
    }
   ]
  },
  {
   "title": "Double transaction",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH ch AS (\n\tSELECT txhash, count(txhash) as c FROM spacebox.raw_transaction\n\tGROUP BY txhash\n)\nSELECT count(*) FROM ch where c != 1"
    }
   ]
  },
  {
   "title": "Double blocks",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 10, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH ch AS (\n\tSELECT height, count(height) as c FROM spacebox.raw_block\n\tGROUP BY height\n)\nSELECT count(*) as count FROM ch WHERE c != 1"
    }
   ]
  },
  {
   "title": "Crawler",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Version",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "spacebox_crawler_version" }
   ]
  },
  {
   "title": "Start height",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 7, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "spacebox_crawler_start_height{job=\"spacebox-crawler\"}"
    }
   ]
  },
  {
   "title": "Stop height",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 12, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "spacebox_crawler_stop_height{job=\"spacebox-crawler\"}"
    }
   ]
  },
  {
   "title": "Workers count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 17, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "spacebox_crawler_total_workers{job=\"spacebox-crawler\"}"
    }
   ]
  },
  {
   "title": "Recovery mode",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "spacebox_crawler_worker_recovery_mode"
    }
   ]
  },
  {
   "title": "Cache length",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "sum by(exported_instance) (spacebox_crawler_cache_length)"
    }
   ]
  },
  {
   "title": "Cache HIT ratio",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 6, "y": 19 },
   "targets": [
    {
     "expr": "sum(rate(spacebox_crawler_global_cache{action=\"hit\"}[$__rate_interval])) / (sum(rate(spacebox_crawler_global_cache{action=\"hit\"}[$__rate_interval])) + sum(rate(spacebox_crawler_global_cache{action=\"miss\"}[$__rate_interval])))"
    }
   ]
  },
  {
   "title": "Cache HIT/MISS global",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 11, "y": 19 },
   "targets": [
    {
     "expr": "sum by(action) (rate(spacebox_crawler_global_cache[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Cache HIT/MISS by instance",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 19 },
   "targets": [
    {
     "expr": "sum by(exported_instance,action) (rate(spacebox_crawler_special_cache[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Last processed height",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "spacebox_crawler_last_processed_block_height{job=\"spacebox-crawler\"}"
    }
   ]
  },
  {
   "title": "HTTP duration 95",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 5, "y": 25 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(request_duration_seconds_bucket[$__rate_interval])))"
    }
   ]
  },
  {
   "title": "Mongo commands duration 95",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 25 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, command) (rate(mongo_commands_bucket[$__rate_interval])))"
    }
   ]
  },
  {
   "title": "Total error messages",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 0, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "spacebox_crawler_total_error_messages{job=\"spacebox-crawler\"}"
    }
   ]
  },
  {
   "title": "Total error tx",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 3, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "spacebox_crawler_total_error_txs{job=\"spacebox-crawler\"}"
    }
   ]
  },
  {
   "title": "GRPC duration 95",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 19, "x": 5, "y": 31 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, grpc_method) (rate(grpc_client_handling_seconds_bucket[$__rate_interval])))"
    }
   ]
  },
  {
   "title": "Block by status",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 19, "x": 5, "y": 37 },
   "targets": [
    {
     "expr": "sum by (status) (spacebox_crawler_blocks_by_status)"
    }
   ]
  },
  {
   "title": "Processing duration 95",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, type) (rate(spacebox_crawler_process_duration_bucket[$__rate_interval])))"
    }
   ]
  },
  {
   "title": "go",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Up Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{job=\"spacebox-crawler\"}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"spacebox-crawler\"}[30s])"
    }
   ]
  },
  {
   "title": "Heap alloc",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "go_memstats_heap_alloc_bytes{job=\"spacebox-crawler\"}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 65 },
   "targets": [
    {
     "expr": "go_goroutines{job=\"spacebox-crawler\"}"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 65 },
   "targets": [
    {
     "expr": "go_threads{job=\"spacebox-crawler\"}"
    }
   ]
  },
  {
   "title": "GC Time Seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(go_gc_duration_seconds_sum{job=\"spacebox-crawler\"}[1m]))"
    }
   ]
  }
 ]
}